name: d9-upgrade-status

services:
  drupal1:
    type: php:7.2
    via: cli
    build:
      - "rm -f composer.lock"
      - "composer install"

  drupal2:
    type: php:7.2
    via: cli

  drupal3:
    type: php:7.2
    via: cli

  drupal4:
    type: php:7.2
    via: cli

tooling:
    
  serve:
    service: :instance
    description: Run D9 Upgrade Status Check against your csv
    cmd:
      - "php /app/web/core/scripts/drupal quick-start minimal --no-interaction --suppress-login"
    options:
      instance:
        default: drupal1
        describe: Run check in different service
        alias:
          - i

  check:
    service: :instance
    description: Run D9 Upgrade Status Check against your csv
    cmd:
      - 'chmod u+w web/sites/default'
      - '/app/vendor/bin/drush pm:enable upgrade_status -y'
      - 'export PATH="/app/vendor/bin:$PATH" && /app/d9upgrade_statuscheckall.sh'
    options:
      instance:
        default: drupal1
        describe: Run check in different instance
        alias:
          - i

excludes:
  - vendor
  - web
  